export const pagesRoutes = [
  ["v-8daa1a0e","/",{"title":"MiraiTravel"},["/index.html","/index.md"]],
  ["v-7618c56f","/announcement/",{"title":"Future V2 : 大致规划 V2 版本开发目标与开发任务与公告"},["/announcement/index.html","/announcement/index.md"]],
  ["v-c850f7e0","/manual/",{"title":"MiraiTravel"},["/manual/index.html","/manual/index.md"]],
  ["v-d7188082","/study/",{"title":"入门"},["/study/index.html","/study/index.md"]],
  ["v-14823ad0","/manual/adapter/",{"title":"MiraiTravel"},["/manual/adapter/index.html","/manual/adapter/index.md"]],
  ["v-1ae232e2","/manual/component/",{"title":""},["/manual/component/index.html","/manual/component/index.md"]],
  ["v-3125414c","/manual/plugin/",{"title":""},["/manual/plugin/index.html","/manual/plugin/index.md"]],
  ["v-7f59da98","/manual/script/",{"title":""},["/manual/script/index.html","/manual/script/index.md"]],
  ["v-5d095102","/study/adapter/",{"title":""},["/study/adapter/index.html","/study/adapter/index.md"]],
  ["v-5238fd98","/study/advice/",{"title":"基础处理逻辑"},["/study/advice/index.html","/study/advice/index.md"]],
  ["v-7e06dfd1","/study/component/",{"title":""},["/study/component/index.html","/study/component/index.md"]],
  ["v-5cc2d6de","/study/consoleDesk/",{"title":""},["/study/consoleDesk/index.html","/study/consoleDesk/index.md"]],
  ["v-087c2425","/study/script/",{"title":""},["/study/script/index.html","/study/script/index.md"]],
  ["v-794e52bd","/study/plugin/",{"title":""},["/study/plugin/index.html","/study/plugin/index.md"]],
  ["v-c2096582","/manual/adapter/QQ/",{"title":"MiraiTravel"},["/manual/adapter/QQ/index.html","/manual/adapter/QQ/index.md"]],
  ["v-1dd213f4","/study/course/mirai/",{"title":""},["/study/course/mirai/index.html","/study/course/mirai/index.md"]],
  ["v-8c363a9a","/manual/adapter/QQ/standard/",{"title":"QQ适配器标准接口手册"},["/manual/adapter/QQ/standard/index.html","/manual/adapter/QQ/standard/index.md"]],
  ["v-7242a1ba","/manual/adapter/QQ/standard/basic/QQObjInterface.html",{"title":"QQObjInterface (QQ机器人对象接口定义)"},["/manual/adapter/QQ/standard/basic/QQObjInterface","/manual/adapter/QQ/standard/basic/QQObjInterface.md"]],
  ["v-3706649a","/404.html",{"title":""},["/404"]],
]
